apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: helenanogueira
spec:
  selector:
    app: playlist-recomendada
  type: NodePort
  ports:
    - protocol: TCP
      port: 40401
      targetPort: 5000
      nodePort: 40401