apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: helenanogueira
spec:
  selector:
    app: recomendador
  type: NodePort
  ports:
    - protocol: TCP
      port: 44444
      targetPort: 5000
      nodePort: 44444